#Semantic Analysis Tools
Taking in stream of words in the form of pkl file. Applying cosine similarity, then placing it on a table.

##Setup

In [3]:
!mkdir embeddings
!cd embeddings
#!curl -o eng-fiction-all_sgns.zip http://snap.stanford.edu/historical_embeddings/eng-fiction-all_sgns.zip
#!unzip eng-fiction-all_sgns.zip
#!mv sgns eng-fiction-all_sgns

!curl -o eng-fiction-all.zip http://snap.stanford.edu/historical_embeddings/eng-fiction-all.zip
!unzip eng-fiction-all.zip

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2503M  100 2503M    0     0  61.3M      0  0:00:40  0:00:40 --:--:-- 89.3M
Archive:  eng-fiction-all.zip
   creating: eng-fiction-all/
   creating: eng-fiction-all/netstats/
  inflating: eng-fiction-all/netstats/full-nstop_nproper-top10000.pkl
   creating: eng-fiction-all/svd/
  inflating: eng-fiction-all/svd/1860-vocab.pkl
  inflating: eng-fiction-all/svd/1900-vocab.pkl
  inflating: eng-fiction-all/svd/1860-w.npy
  inflating: eng-fiction-all/svd/1900-w.npy
  inflating: eng-fiction-all/svd/1840-w.npy
  inflating: eng-fiction-all/svd/1920-w.npy
  inflating: eng-fiction-all/svd/1890-w.npy
  inflating: eng-fiction-all/svd/1970-vocab.pkl
  inflating: eng-fiction-all/svd/1810-vocab.pkl
  inflating: eng-fiction-all/svd/1940-w.npy
  inflating: eng-fiction-all/svd/1920-vocab.pkl
  inflating: eng-fiction-all/svd/1840-vocab.pkl
  inflating: eng-fiction-all/svd/1990-w.npy
  inflating: eng-fiction-all/svd/1820-w.npy
  inflating: eng-fiction-all/svd/1990-vocab.pkl
  inflating: eng-fiction-all/svd/1880-vocab.pkl
  inflating: eng-fiction-all/svd/1960-w.npy
  inflating: eng-fiction-all/svd/1800-w.npy
  inflating: eng-fiction-all/svd/1830-vocab.pkl
  inflating: eng-fiction-all/svd/1950-vocab.pkl
  inflating: eng-fiction-all/svd/1890-vocab.pkl
  inflating: eng-fiction-all/svd/1980-w.npy
  inflating: eng-fiction-all/svd/1820-vocab.pkl
  inflating: eng-fiction-all/svd/1830-w.npy
  inflating: eng-fiction-all/svd/1940-vocab.pkl
  inflating: eng-fiction-all/svd/1950-w.npy
  inflating: eng-fiction-all/svd/1930-vocab.pkl
  inflating: eng-fiction-all/svd/1850-vocab.pkl
  inflating: eng-fiction-all/svd/1810-w.npy
  inflating: eng-fiction-all/svd/1980-vocab.pkl
  inflating: eng-fiction-all/svd/1970-w.npy
  inflating: eng-fiction-all/svd/1910-w.npy
  inflating: eng-fiction-all/svd/1870-w.npy
  inflating: eng-fiction-all/svd/1960-vocab.pkl
  inflating: eng-fiction-all/svd/1800-vocab.pkl
  inflating: eng-fiction-all/svd/1870-vocab.pkl
  inflating: eng-fiction-all/svd/1910-vocab.pkl
  inflating: eng-fiction-all/svd/1930-w.npy
  inflating: eng-fiction-all/svd/1880-w.npy
  inflating: eng-fiction-all/svd/1850-w.npy
   creating: eng-fiction-all/pos/
  inflating: eng-fiction-all/pos/1840-pos_counts.pkl
  inflating: eng-fiction-all/pos/1960-pos.pkl
  inflating: eng-fiction-all/pos/1990-pos.pkl
  inflating: eng-fiction-all/pos/1890-pos.pkl
  inflating: eng-fiction-all/pos/1860-pos.pkl
  inflating: eng-fiction-all/pos/1940-pos_counts.pkl
  inflating: eng-fiction-all/pos/1810-pos.pkl
  inflating: eng-fiction-all/pos/1910-pos.pkl
  inflating: eng-fiction-all/pos/1850-pos_counts.pkl
  inflating: eng-fiction-all/pos/1950-pos_counts.pkl
  inflating: eng-fiction-all/pos/1880-pos_counts.pkl
  inflating: eng-fiction-all/pos/1960-pos_counts.pkl
  inflating: eng-fiction-all/pos/1980-pos.pkl
  inflating: eng-fiction-all/pos/1970-pos.pkl
  inflating: eng-fiction-all/pos/1860-pos_counts.pkl
  inflating: eng-fiction-all/pos/1870-pos.pkl
  inflating: eng-fiction-all/pos/1980-pos_counts.pkl
  inflating: eng-fiction-all/pos/1880-pos.pkl
  inflating: eng-fiction-all/pos/1970-pos_counts.pkl
  inflating: eng-fiction-all/pos/1890-pos_counts.pkl
  inflating: eng-fiction-all/pos/1990-pos_counts.pkl
  inflating: eng-fiction-all/pos/1870-pos_counts.pkl
  inflating: eng-fiction-all/pos/1800-pos.pkl
  inflating: eng-fiction-all/pos/1900-pos.pkl
  inflating: eng-fiction-all/pos/1830-pos.pkl
  inflating: eng-fiction-all/pos/1930-pos.pkl
  inflating: eng-fiction-all/pos/1910-pos_counts.pkl
  inflating: eng-fiction-all/pos/1810-pos_counts.pkl
  inflating: eng-fiction-all/pos/1900-pos_counts.pkl
  inflating: eng-fiction-all/pos/1940-pos.pkl
  inflating: eng-fiction-all/pos/1840-pos.pkl
  inflating: eng-fiction-all/pos/1800-pos_counts.pkl
  inflating: eng-fiction-all/pos/1830-pos_counts.pkl
  inflating: eng-fiction-all/pos/1820-pos.pkl
  inflating: eng-fiction-all/pos/1930-pos_counts.pkl
  inflating: eng-fiction-all/pos/1920-pos.pkl
  inflating: eng-fiction-all/pos/1820-pos_counts.pkl
  inflating: eng-fiction-all/pos/1950-pos.pkl
  inflating: eng-fiction-all/pos/1920-pos_counts.pkl
  inflating: eng-fiction-all/pos/1850-pos.pkl
  inflating: eng-fiction-all/freqs.pkl
  inflating: eng-fiction-all/avg_freqs.pkl
   creating: eng-fiction-all/sgns/
  inflating: eng-fiction-all/sgns/1990-vocab.pkl
  inflating: eng-fiction-all/sgns/1970-w.npy
  inflating: eng-fiction-all/sgns/1810-w.npy
  inflating: eng-fiction-all/sgns/1840-vocab.pkl
  inflating: eng-fiction-all/sgns/1920-vocab.pkl
  inflating: eng-fiction-all/sgns/1950-w.npy
  inflating: eng-fiction-all/sgns/1980-w.npy
  inflating: eng-fiction-all/sgns/1950-vocab.pkl
  inflating: eng-fiction-all/sgns/1830-w.npy
  inflating: eng-fiction-all/sgns/1830-vocab.pkl
  inflating: eng-fiction-all/sgns/1880-vocab.pkl
  inflating: eng-fiction-all/sgns/1850-w.npy
  inflating: eng-fiction-all/sgns/1930-w.npy
  inflating: eng-fiction-all/sgns/1880-w.npy
  inflating: eng-fiction-all/sgns/1900-vocab.pkl
  inflating: eng-fiction-all/sgns/1860-vocab.pkl
  inflating: eng-fiction-all/sgns/1870-w.npy
  inflating: eng-fiction-all/sgns/1810-vocab.pkl
  inflating: eng-fiction-all/sgns/1970-vocab.pkl
  inflating: eng-fiction-all/sgns/1910-w.npy
  inflating: eng-fiction-all/sgns/1800-vocab.pkl
  inflating: eng-fiction-all/sgns/1960-vocab.pkl
  inflating: eng-fiction-all/sgns/1920-w.npy
  inflating: eng-fiction-all/sgns/1890-w.npy
  inflating: eng-fiction-all/sgns/1840-w.npy
  inflating: eng-fiction-all/sgns/1900-w.npy
  inflating: eng-fiction-all/sgns/1910-vocab.pkl
  inflating: eng-fiction-all/sgns/1870-vocab.pkl
  inflating: eng-fiction-all/sgns/1860-w.npy
  inflating: eng-fiction-all/sgns/1940-vocab.pkl
  inflating: eng-fiction-all/sgns/1820-vocab.pkl
  inflating: eng-fiction-all/sgns/1800-w.npy
  inflating: eng-fiction-all/sgns/1890-vocab.pkl
  inflating: eng-fiction-all/sgns/1960-w.npy
  inflating: eng-fiction-all/sgns/1980-vocab.pkl
  inflating: eng-fiction-all/sgns/1850-vocab.pkl
  inflating: eng-fiction-all/sgns/1930-vocab.pkl
  inflating: eng-fiction-all/sgns/1990-w.npy
  inflating: eng-fiction-all/sgns/1820-w.npy
  inflating: eng-fiction-all/sgns/1940-w.npy
   creating: eng-fiction-all/volstats/
  inflating: eng-fiction-all/volstats/vols.pkl
  inflating: eng-fiction-all/volstats/disps.pkl
   creating: eng-fiction-all/counts/
  inflating: eng-fiction-all/counts/1830-counts.pkl
  inflating: eng-fiction-all/counts/1930-counts.pkl
  inflating: eng-fiction-all/counts/1910-counts.pkl
  inflating: eng-fiction-all/counts/1810-counts.pkl
  inflating: eng-fiction-all/counts/1870-counts.pkl
  inflating: eng-fiction-all/counts/1880-counts.pkl
  inflating: eng-fiction-all/counts/1980-counts.pkl
  inflating: eng-fiction-all/counts/1970-counts.pkl
  inflating: eng-fiction-all/counts/1950-counts.pkl
  inflating: eng-fiction-all/counts/1850-counts.pkl
  inflating: eng-fiction-all/counts/1960-counts.pkl
  inflating: eng-fiction-all/counts/1990-counts.pkl
  inflating: eng-fiction-all/counts/1890-counts.pkl
  inflating: eng-fiction-all/counts/1860-counts.pkl
  inflating: eng-fiction-all/counts/1840-counts.pkl
  inflating: eng-fiction-all/counts/1940-counts.pkl
  inflating: eng-fiction-all/counts/1920-counts.pkl
  inflating: eng-fiction-all/counts/1820-counts.pkl
  inflating: eng-fiction-all/counts/1800-counts.pkl
  inflating: eng-fiction-all/counts/1900-counts.pkl
   creating: eng-fiction-all/ppmi/
  inflating: eng-fiction-all/ppmi/1960.bin
  inflating: eng-fiction-all/ppmi/1920.bin
  inflating: eng-fiction-all/ppmi/1810-index.pkl
  inflating: eng-fiction-all/ppmi/1970-index.pkl
  inflating: eng-fiction-all/ppmi/1860.bin
  inflating: eng-fiction-all/ppmi/1900-index.pkl
  inflating: eng-fiction-all/ppmi/1860-index.pkl
  inflating: eng-fiction-all/ppmi/1820.bin
  inflating: eng-fiction-all/ppmi/1870.bin
  inflating: eng-fiction-all/ppmi/1880-index.pkl
  inflating: eng-fiction-all/ppmi/1950-index.pkl
  inflating: eng-fiction-all/ppmi/1830-index.pkl
  inflating: eng-fiction-all/ppmi/1830.bin
  inflating: eng-fiction-all/ppmi/1840-index.pkl
  inflating: eng-fiction-all/ppmi/1970.bin
  inflating: eng-fiction-all/ppmi/1920-index.pkl
  inflating: eng-fiction-all/ppmi/1930.bin
  inflating: eng-fiction-all/ppmi/1990-index.pkl
  inflating: eng-fiction-all/ppmi/1850.bin
  inflating: eng-fiction-all/ppmi/1850-index.pkl
  inflating: eng-fiction-all/ppmi/1930-index.pkl
  inflating: eng-fiction-all/ppmi/1980-index.pkl
  inflating: eng-fiction-all/ppmi/1810.bin
  inflating: eng-fiction-all/ppmi/1990.bin
  inflating: eng-fiction-all/ppmi/1950.bin
  inflating: eng-fiction-all/ppmi/1890-index.pkl
  inflating: eng-fiction-all/ppmi/1910.bin
  inflating: eng-fiction-all/ppmi/1940-index.pkl
  inflating: eng-fiction-all/ppmi/1820-index.pkl
  inflating: eng-fiction-all/ppmi/1890.bin
  inflating: eng-fiction-all/ppmi/1940.bin
  inflating: eng-fiction-all/ppmi/1910-index.pkl
  inflating: eng-fiction-all/ppmi/1870-index.pkl
  inflating: eng-fiction-all/ppmi/1900.bin
  inflating: eng-fiction-all/ppmi/1880.bin
  inflating: eng-fiction-all/ppmi/1840.bin
  inflating: eng-fiction-all/ppmi/1800-index.pkl
  inflating: eng-fiction-all/ppmi/1960-index.pkl
  inflating: eng-fiction-all/ppmi/1800.bin
  inflating: eng-fiction-all/ppmi/1980.bin
   creating: eng-fiction-all/word_lists/
  inflating: eng-fiction-all/word_lists/full-nstop_nproper.pkl
  inflating: eng-fiction-all/word_lists/full-all.pkl

In [4]:
!pip install --upgrade gensim
!pip install openai

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 57.9 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0
Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.32.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.14.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.13)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)

In [5]:
import numpy as np
import pickle as p
from openai import OpenAI
from google.colab import userdata
from gensim.models import KeyedVectors
import pandas as pd
import random
from IPython.display import display, Markdown

Find minimum frequency words.

In [6]:
with open(f"/content/eng-fiction-all/word_lists/full-nstop_nproper.pkl", "rb") as file:
    clean_words_sorted = p.load(file, encoding="latin1")

with open(f"/content/eng-fiction-all/freqs.pkl", "rb") as file:
    freq_of_words = p.load(file, encoding="latin1")

with open(f"/content/eng-fiction-all/volstats/vols.pkl", "rb") as file:
    score_of_words = p.load(file, encoding="latin1")

In [7]:
selected_decades = [decade for decade in range(1950, 1990+10, 10)]
print(selected_decades)

[1950, 1960, 1970, 1980, 1990]

In [8]:
top_freq_words = clean_words_sorted[:10000]
sanitized_top_freq_words = top_freq_words

In [9]:
for word in score_of_words:
  for decade in selected_decades:
    if np.isnan(score_of_words[word][decade]):
      if word in sanitized_top_freq_words:
        sanitized_top_freq_words.remove(word)

In [10]:
def avg_angular_shift_distance(key):
  cumulative_distance_shift = 0
  for decade in selected_decades:
    cumulative_distance_shift += np.arccos(np.clip(score_of_words[key][decade],-1, 1))
  avg_shift_distance = cumulative_distance_shift/len(selected_decades)
  return avg_shift_distance

In [11]:
shift_list = []

for word in sanitized_top_freq_words:
  shift_list.append([word, avg_angular_shift_distance(word)])

shift_list = sorted(shift_list,key=lambda x: x[1], reverse=True)

In [12]:
print(shift_list)
print(len(shift_list))

percentile = 0.25

low_shift_words = shift_list[int(len(shift_list)-len(shift_list)*percentile):]
high_shift_words = shift_list[:int(len(shift_list)*percentile)]

print(low_shift_words)
print(high_shift_words)
print(len(low_shift_words),len(high_shift_words))

[['wherein', np.float64(1.0592824037683477)], ['invariably', np.float64(1.0380107762865807)], ['likewise', np.float64(1.0317762059178455)], ['doubtless', np.float64(1.0284287033443518)], ['termed', np.float64(1.016898483526426)], ['speedily', np.float64(1.0107858998691188)], ['sombre', np.float64(0.9952735129375126)], ['flora', np.float64(0.9927531314376881)], ['dick', np.float64(0.9920668464134084)], ['travellers', np.float64(0.9920098299343003)], ['captive', np.float64(0.9907007008999514)], ['seemingly', np.float64(0.9904354099961381)], ['formerly', np.float64(0.97655241415905)], ['airy', np.float64(0.9752334010549083)], ['consequently', np.float64(0.9734308447723443)], ['walker', np.float64(0.9726497393953505)], ['hugh', np.float64(0.9711309308552073)], ['schoolmaster', np.float64(0.9683373517831646)], ['positively', np.float64(0.9672964646472894)], ['thereby', np.float64(0.9671843263191118)], ['lone', np.float64(0.9670576584420993)], ['majestic', np.float64(0.9603236949131866)], ['dusky', np.float64(0.9578708193124521)], ['possessing', np.float64(0.9565580613776298)], ['visage', np.float64(0.9560772771627943)], ['monarch', np.float64(0.9559388105439931)], ['unseen', np.float64(0.9554821215574785)], ['visibly', np.float64(0.9549926333321656)], ['commonly', np.float64(0.9535063383453133)], ['therein', np.float64(0.9534873476959105)], ['represented', np.float64(0.951701568961106)], ['maidens', np.float64(0.951664391823333)], ['lucy', np.float64(0.9510026059322261)], ['mentally', np.float64(0.9508754479075234)], ['comparatively', np.float64(0.9506158981435655)], ['underneath', np.float64(0.9502957999971795)], ['enchanted', np.float64(0.9498771738036762)], ['affecting', np.float64(0.9497377788682553)], ['pike', np.float64(0.9493376347009411)], ['privately', np.float64(0.9476462310733063)], ['horribly', np.float64(0.9466217594111749)], ['kit', np.float64(0.9464106086714155)], ['balloon', np.float64(0.9462024145850565)], ['inasmuch', np.float64(0.9456151721862811)], ['unfinished', np.float64(0.9429413460432123)], ['secretly', np.float64(0.9428828334392703)], ['obscure', np.float64(0.9428350888672405)], ['resembled', np.float64(0.9425340496496654)], ['inevitably', np.float64(0.9418022976689688)], ['attendant', np.float64(0.9416637883184104)], ['sublime', np.float64(0.9412128240932649)], ['exhibited', np.float64(0.9405734895545077)], ['harmless', np.float64(0.9404970310762686)], ['regards', np.float64(0.9402094153949939)], ['conductor', np.float64(0.939681518533795)], ['thrice', np.float64(0.9389000291814302)], ['fairly', np.float64(0.9386000882469613)], ['wonderfully', np.float64(0.9383840442930758)], ['whereas', np.float64(0.9378159100508843)], ['perpetually', np.float64(0.93689643430366)], ['undoubtedly', np.float64(0.9368931489690897)], ['unconsciously', np.float64(0.9358230606830655)], ['contemplated', np.float64(0.9351078858824632)], ['meek', np.float64(0.934413351399866)], ['notwithstanding', np.float64(0.9327295146324012)], ['venerable', np.float64(0.9325254861637353)], ['heathen', np.float64(0.9322298599115513)], ['beautifully', np.float64(0.9321436823395748)], ['engaging', np.float64(0.9319065574804994)], ['luckily', np.float64(0.9309865658157236)], ['shepherd', np.float64(0.9309523388439471)], ['supposing', np.float64(0.9308718862908234)], ['foe', np.float64(0.9303260987031617)], ['stony', np.float64(0.9294080862454024)], ['companionship', np.float64(0.929158211833661)], ['repeatedly', np.float64(0.9285940156910636)], ['infernal', np.float64(0.9285213611598067)], ['whereupon', np.float64(0.9284405347809784)], ['boast', np.float64(0.926851155316211)], ['formidable', np.float64(0.9268282804211345)], ['tolerable', np.float64(0.9267990755779355)], ['screw', np.float64(0.9267065585231556)], ['mortals', np.float64(0.9257982100042043)], ['sentiment', np.float64(0.9252843145547416)], ['whereof', np.float64(0.924965111108869)], ['imperfect', np.float64(0.9248689476136359)], ['daisy', np.float64(0.9248032445476613)], ['forthwith', np.float64(0.9247033963138727)], ['proceeding', np.float64(0.9246604709451599)], ['fiery', np.float64(0.924572664399727)], ['embodied', np.float64(0.924500619931665)], ['subdued', np.float64(0.9244925323580417)], ['sage', np.float64(0.924448209855343)], ['pupil', np.float64(0.923480782609438)], ['inwardly', np.float64(0.9232508953826226)], ['rob', np.float64(0.9231304691052747)], ['martial', np.float64(0.9223735285758927)], ['singularly', np.float64(0.9207516584866582)], ['savage', np.float64(0.9207448626409713)], ['conquest', np.float64(0.9200528090502814)], ['skies', np.float64(0.9199793985437104)], ['meets', np.float64(0.9199688735335638)], ['proclaimed', np.float64(0.9199340444169002)], ['designs', np.float64(0.919886444093527)], ['specially', np.float64(0.9197304633916294)], ['appalling', np.float64(0.919530046261969)], ['unlucky', np.float64(0.9189172162620942)], ['sally', np.float64(0.9183656564153706)], ['meantime', np.float64(0.9181217980727123)], ['retiring', np.float64(0.9177433217900817)], ['sue', np.float64(0.9157576134510436)], ['ken', np.float64(0.9153284204519524)], ['boldly', np.float64(0.915313685603121)], ['abstract', np.float64(0.9151857261180103)], ['accidental', np.float64(0.9150770455542137)], ['customer', np.float64(0.9149196143800887)], ['baker', np.float64(0.9146202687876812)], ['perceiving', np.float64(0.9141247397975404)], ['justly', np.float64(0.9140222673212511)], ['heath', np.float64(0.9138339826924657)], ['occasionally', np.float64(0.913576288306133)], ['veiled', np.float64(0.9128298210150791)], ['associates', np.float64(0.9123926657141237)], ['ghostly', np.float64(0.91222070065801)], ['fearful', np.float64(0.9113700042701197)], ['accompanying', np.float64(0.9109846082187225)], ['involuntarily', np.float64(0.9109814679198062)], ['admirable', np.float64(0.9108731937740918)], ['miniature', np.float64(0.9106158619468999)], ['warriors', np.float64(0.9102206330505987)], ['imitation', np.float64(0.9101284823206328)], ['thence', np.float64(0.9098940812074241)], ['equally', np.float64(0.9095319348539654)], ['breaks', np.float64(0.9095287818909507)], ['preference', np.float64(0.9089548454746511)], ['representing', np.float64(0.9085361912132299)], ['faithfully', np.float64(0.9083493880487066)], ['reckoning', np.float64(0.9081257840961108)], ['pilgrim', np.float64(0.9080591532853111)], ['patron', np.float64(0.9079020406301781)], ['robin', np.float64(0.9076842459081769)], ['beforehand', np.float64(0.9076150932089175)], ['thereupon', np.float64(0.9073954793102382)], ['offensive', np.float64(0.9070962992583247)], ['animated', np.float64(0.9067195909412866)], ['familiarity', np.float64(0.9065951138062923)], ['antique', np.float64(0.9065514055788407)], ['reserve', np.float64(0.9062466674776302)], ['assisted', np.float64(0.9055301793859831)], ['matron', np.float64(0.9055265318818309)], ['universal', np.float64(0.9052271374113042)], ['multitude', np.float64(0.905221614175351)], ['shrinking', np.float64(0.9051958927042459)], ['sundry', np.float64(0.9047679054850842)], ['resembling', np.float64(0.9044016821274727)], ['entry', np.float64(0.9042845384943474)], ['comrade', np.float64(0.9042776218840759)], ['scots', np.float64(0.9042531328494505)], ['hence', np.float64(0.9042355649528198)], ['gallantry', np.float64(0.9040415402485383)], ['duly', np.float64(0.9034593499441149)], ['presumed', np.float64(0.903076024355548)], ['forcibly', np.float64(0.9030708918506047)], ['immortal', np.float64(0.9029022596954445)], ['applying', np.float64(0.9025215600757784)], ['crush', np.float64(0.9022562160053942)], ['ghastly', np.float64(0.9021316441794374)], ['necessarily', np.float64(0.9018663331159342)], ['uses', np.float64(0.9017560342809805)], ['delights', np.float64(0.9017141445174494)], ['traveller', np.float64(0.9016972802952266)], ['passes', np.float64(0.9012868983537464)], ['morbid', np.float64(0.9012059111099943)], ['dwarf', np.float64(0.9011491824347713)], ['childish', np.float64(0.9011326696166698)], ['damsel', np.float64(0.9011302446471842)], ['partial', np.float64(0.9010718075453117)], ['flattering', np.float64(0.9009739319377115)], ['represent', np.float64(0.8998013268964897)], ['barber', np.float64(0.899567212983532)], ['manifest', np.float64(0.8995011885890781)], ['prairie', np.float64(0.8994424195173935)], ['hints', np.float64(0.8993016776216628)], ['seeming', np.float64(0.8985606136493377)], ['employment', np.float64(0.898472450758177)], ['eloquence', np.float64(0.8984242281964487)], ['mournful', np.float64(0.898240838407423)], ['permanent', np.float64(0.8979912823116907)], ['promising', np.float64(0.8979736712823037)], ['accidentally', np.float64(0.8969595374926284)], ['extravagant', np.float64(0.8966370926811992)], ['foreigner', np.float64(0.8964596563974151)], ['bidding', np.float64(0.896384875891712)], ['profoundly', np.float64(0.8962734064530749)], ['ambitious', np.float64(0.8960703679651594)], ['serenity', np.float64(0.8960142116570026)], ['prompt', np.float64(0.895969877784647)], ['associate', np.float64(0.8957250870128913)], ['yonder', np.float64(0.8955913918130871)], ['burns', np.float64(0.8954064253442663)], ['foremost', np.float64(0.8949799750827138)], ['ere', np.float64(0.8946543153369442)], ['decidedly', np.float64(0.8938319273357846)], ['imaginary', np.float64(0.8937498811955196)], ['coloured', np.float64(0.8937365030485035)], ['exaggerated', np.float64(0.8936346800201145)], ['disclosed', np.float64(0.8935865584261764)], ['novelty', np.float64(0.8932619709931231)], ['practised', np.float64(0.8931198922667782)], ['suggesting', np.float64(0.8930144442493082)], ['monks', np.float64(0.8924061485562378)], ['homely', np.float64(0.8921079943321665)], ['exhibition', np.float64(0.8919947122218643)], ['lily', np.float64(0.8914980053886128)], ['paradise', np.float64(0.8910837146408929)], ['alike', np.float64(0.8910824217011634)], ['justified', np.float64(0.8907161329139861)], ['rival', np.float64(0.8906778309605219)], ['void', np.float64(0.8905673548108244)], ['strangely', np.float64(0.8904324865776225)], ['lent', np.float64(0.8898486935614599)], ['identical', np.float64(0.889788104800003)], ['graces', np.float64(0.8897497825650923)], ['generally', np.float64(0.889658350367508)], ['boon', np.float64(0.8895311257685663)], ['rapture', np.float64(0.8892545673100392)], ['wisely', np.float64(0.889199525294418)], ['sinister', np.float64(0.8891938718406088)], ['manhood', np.float64(0.8886600176885742)], ['exceeding', np.float64(0.8884886342308572)], ['tenants', np.float64(0.8884822685928817)], ['recognised', np.float64(0.8879689955967361)], ['bands', np.float64(0.887960921266496)], ['grandeur', np.float64(0.8879251920659981)], ['genteel', np.float64(0.887775568086384)], ['excess', np.float64(0.8877284479055418)], ['conspicuous', np.float64(0.8876210984538881)], ['uncommon', np.float64(0.8873564655992426)], ['quaint', np.float64(0.8873223139496262)], ['practically', np.float64(0.8870317586527374)], ['woe', np.float64(0.8870249430138847)], ['lustre', np.float64(0.8869954532017802)], ['mortal', np.float64(0.8869804663127517)], ['failing', np.float64(0.8869146304801907)], ['unnatural', np.float64(0.8868464393977759)], ['physically', np.float64(0.8868411809254073)], ['moreover', np.float64(0.886735733520382)], ['hardened', np.float64(0.8865735215266959)], ['evidently', np.float64(0.8864870745279761)], ['illustrated', np.float64(0.886416915485545)], ['extensive', np.float64(0.8863740405920761)], ['stamp', np.float64(0.886281758452683)], ['host', np.float64(0.886264906548722)], ['imparted', np.float64(0.8862623083321155)], ['beauties', np.float64(0.886160759140471)], ['characteristic', np.float64(0.8861148864132218)], ['institution', np.float64(0.8860972726493201)], ['addresses', np.float64(0.8860135810717477)], ['establishment', np.float64(0.8859994103681048)], ['namely', np.float64(0.885578648339248)], ['cheerfulness', np.float64(0.885494150222543)], ['bestowed', np.float64(0.8854906222723503)], ['charmed', np.float64(0.8851912115342733)], ['doth', np.float64(0.8851456107394545)], ['trifle', np.float64(0.8850198512199382)], ['youthful', np.float64(0.8841437477956247)], ['peculiarly', np.float64(0.883986633201135)], ['asserted', np.float64(0.883947616949443)], ['influences', np.float64(0.8838565053573724)], ['associations', np.float64(0.88375646850964)], ['exalted', np.float64(0.8836149000904753)], ['unbroken', np.float64(0.8834709535051275)], ['domestic', np.float64(0.883364209640398)], ['prodigious', np.float64(0.8831928396025003)], ['jest', np.float64(0.8828245796626881)], ['aversion', np.float64(0.882774107528574)], ['mould', np.float64(0.8826150568048211)], ['cease', np.float64(0.8825716470849461)], ['chivalry', np.float64(0.8825501034171557)], ['innumerable', np.float64(0.882545082590662)], ['production', np.float64(0.8820149450181963)], ['neglected', np.float64(0.8819470348721941)], ['seaman', np.float64(0.8819423333615033)], ['habitual', np.float64(0.881937774437359)], ['neglect', np.float64(0.8818325443211954)], ['reckless', np.float64(0.8818199439647028)], ['wrongs', np.float64(0.8817705544193478)], ['horrid', np.float64(0.8817628000202908)], ['elevated', np.float64(0.8815625144169659)], ['artificial', np.float64(0.8813876450035819)], ['odious', np.float64(0.8813606526842431)], ['afar', np.float64(0.881118045505519)], ['handy', np.float64(0.8811017310266467)], ['suggestions', np.float64(0.8810881810357241)], ['baron', np.float64(0.880892095021216)], ['greatness', np.float64(0.8806282994818815)], ['admission', np.float64(0.8805204838654752)], ['forms', np.float64(0.8803730605025452)], ['endless', np.float64(0.879639278155414)], ['devils', np.float64(0.8795974552313452)], ['gross', np.float64(0.8792343482613971)], ['select', np.float64(0.8788677548864244)], ['fancied', np.float64(0.8788530039056379)], ['astonishing', np.float64(0.8783724134445741)], ['appropriate', np.float64(0.8783655642189366)], ['hostile', np.float64(0.8783635095659624)], ['ordering', np.float64(0.8782121460251828)], ['pirates', np.float64(0.8781369816112081)], ['deemed', np.float64(0.877779239525788)], ['scales', np.float64(0.8775859057838089)], ['heather', np.float64(0.8774448900722973)], ['bachelor', np.float64(0.8773671920363013)], ['regularly', np.float64(0.8773011622095916)], ['picturesque', np.float64(0.8772787407470755)], ['retained', np.float64(0.8766827548700183)], ['comforts', np.float64(0.8765154555170487)], ['supplied', np.float64(0.8764852243143018)], ['haughty', np.float64(0.8762170668274585)], ['amongst', np.float64(0.8758168346795244)], ['scarce', np.float64(0.875807900608174)], ['perpetual', np.float64(0.8757942294345951)], ['internal', np.float64(0.8755084147984326)], ['governess', np.float64(0.8753523607799714)], ['perilous', np.float64(0.8751144313476613)], ['measures', np.float64(0.8750734332124134)], ['partially', np.float64(0.8750161669772669)], ['petty', np.float64(0.8749239863967689)], ['exercised', np.float64(0.874718648352413)], ['sustained', np.float64(0.8747147976372676)], ['abuse', np.float64(0.8747018874207608)], ['nowadays', np.float64(0.8744677043616387)], ['resolve', np.float64(0.8744249552210194)], ['butler', np.float64(0.8742770818422219)], ['triumphant', np.float64(0.8742508881203467)], ['abominable', np.float64(0.8741441473043295)], ['workmen', np.float64(0.874113442224567)], ['feminine', np.float64(0.8741123492209922)], ['everlasting', np.float64(0.8739096165840815)], ['essentially', np.float64(0.8737085867493397)], ['contemplation', np.float64(0.8732936924272613)], ['hideous', np.float64(0.8732155992007057)], ['insane', np.float64(0.8732121912458473)], ['objected', np.float64(0.8732064288514237)], ['severity', np.float64(0.872995215621421)], ['rip', np.float64(0.8728961708839028)], ['seldom', np.float64(0.8728017691413958)], ['missionary', np.float64(0.8726642556669262)], ['compass', np.float64(0.8725540708289674)], ['diet', np.float64(0.8725237277226396)], ['personage', np.float64(0.8724018863755459)], ['desirous', np.float64(0.872376556039878)], ['masters', np.float64(0.8722409370916671)], ['capacity', np.float64(0.8720003041535961)], ['sentimental', np.float64(0.871711655533921)], ['ominous', np.float64(0.8713785032458169)], ['reckoned', np.float64(0.8711920114651942)], ['wherever', np.float64(0.8710403296908729)], ['enlarged', np.float64(0.8710230367618446)], ['carrier', np.float64(0.8710117957249075)], ['rightly', np.float64(0.8708596491601469)], ['englishmen', np.float64(0.8706549586399145)], ['confounded', np.float64(0.8704415439313072)], ['chiefly', np.float64(0.8704078035936664)], ['flourish', np.float64(0.8701625950497694)], ['actual', np.float64(0.8701491613018675)], ['substantial', np.float64(0.8700323218771174)], ['declaring', np.float64(0.8699314211598782)], ['horrors', np.float64(0.8698998415960599)], ['device', np.float64(0.8698567130362947)], ['alarming', np.float64(0.8698410216512157)], ['honoured', np.float64(0.8695935625466881)], ['bridegroom', np.float64(0.8695239728820375)], ['fisherman', np.float64(0.8693843351519845)], ['hereafter', np.float64(0.8692704811598254)], ['barbarous', np.float64(0.8692441107583473)], ['melting', np.float64(0.8691524581545378)], ['substance', np.float64(0.8690853891143165)], ['monstrous', np.float64(0.8689090146296342)], ['prophet', np.float64(0.8688800298756968)], ['handling', np.float64(0.8686446241577714)], ['pretence', np.float64(0.8685814001113116)], ['buck', np.float64(0.8684514106795067)], ['concealment', np.float64(0.8683590772125127)], ['viewed', np.float64(0.8681736434986682)], ['pilgrims', np.float64(0.8681478014963087)], ['sympathetic', np.float64(0.8679981993810444)], ['lunatic', np.float64(0.867975269755043)], ['carries', np.float64(0.8679392777592925)], ['accordingly', np.float64(0.8677895140939835)], ['transparent', np.float64(0.8676427064254429)], ['refreshment', np.float64(0.8676192743470782)], ['animation', np.float64(0.8675485988556652)], ['mechanically', np.float64(0.8674776503814845)], ['touches', np.float64(0.867421873270318)], ['prolonged', np.float64(0.8673782490605502)], ['sufficiently', np.float64(0.8668760031461146)], ['previously', np.float64(0.8668636521994483)], ['wickedness', np.float64(0.8668324700288078)], ['perspective', np.float64(0.8668203710833581)], ['literally', np.float64(0.8667470937312531)], ['zeal', np.float64(0.8666429823231894)], ['additional', np.float64(0.8665234241336748)], ['pictured', np.float64(0.8664987043990902)], ['guardian', np.float64(0.8664023369922255)], ['plea', np.float64(0.8663914404022733)], ['darkly', np.float64(0.866325447628844)], ['appealing', np.float64(0.866137287778742)], ['bravely', np.float64(0.8659895005922161)], ['fantastic', np.float64(0.8656804763453223)], ['assented', np.float64(0.8655762666894364)], ['pious', np.float64(0.8655522346124223)], ['sorrowful', np.float64(0.8655263159916491)], ['renewed', np.float64(0.8654998953580642)], ['presenting', np.float64(0.8654560019344346)], ['customary', np.float64(0.8654313061128599)], ['fashionable', np.float64(0.8651857008543786)], ['recommended', np.float64(0.865103172743378)], ['inconvenient', np.float64(0.8649731672776253)], ['dominion', np.float64(0.8649676156736602)], ['strikes', np.float64(0.8645772460595216)], ['withdrawn', np.float64(0.8645752477179285)], ['correspondent', np.float64(0.8642066316640362)], ['divide', np.float64(0.8640447726566558)], ['vegetable', np.float64(0.8639965232784743)], ['mills', np.float64(0.8639004989800936)], ['pledge', np.float64(0.8638869524586339)], ['remarking', np.float64(0.8638756682115686)], ['tenant', np.float64(0.8637891598001538)], ['bestow', np.float64(0.8637070823969616)], ['skeleton', np.float64(0.8635368252730105)], ['antiquity', np.float64(0.8633718173039113)], ['musical', np.float64(0.8633607533107602)], ['obstinate', np.float64(0.8632460296461477)], ['sensibility', np.float64(0.863196459374441)], ['preliminary', np.float64(0.8631039455871248)], ['contrived', np.float64(0.8628554014655222)], ['discreet', np.float64(0.8627468832155463)], ['eventually', 

In [13]:
seed = 1042
num_words = 50

random.seed(seed)
low_target_word = random.sample(low_shift_words, num_words)
high_target_word = random.sample(high_shift_words, num_words)

print(low_target_word)
print(high_target_word)

random

[['nervous', np.float64(0.5693470723430367)], ['ached', np.float64(0.5824691612551237)], ['chill', np.float64(0.554175758954558)], ['marrying', np.float64(0.5926266744854113)], ['able', np.float64(0.34960250425348444)], ['wheel', np.float64(0.5576721750938181)], ['trees', np.float64(0.40642773677660005)], ['crossed', np.float64(0.562606846642281)], ['country', np.float64(0.5310534508049704)], ['harm', np.float64(0.5482031339962677)], ['bewilderment', np.float64(0.5635864777871481)], ['smiled', np.float64(0.46513614821666655)], ['clinging', np.float64(0.5790510255311011)], ['bright', np.float64(0.532959985662286)], ['collapsed', np.float64(0.5341297576402443)], ['power', np.float64(0.578741033628624)], ['glistened', np.float64(0.5595704570619211)], ['bet', np.float64(0.5040401808317025)], ['friends', np.float64(0.4732909883843714)], ['tone', np.float64(0.5287018153056542)], ['bathroom', np.float64(0.41060132469443894)], ['reign', np.float64(0.5321545969800137)], ['forgotten', np.float64(0.5658561120154288)], ['peace', np.float64(0.5968296181918376)], ['father', np.float64(0.41492519617918655)], ['achieve', np.float64(0.5916166315933207)], ['m', np.float64(0.5536423505803006)], ['shirts', np.float64(0.5688436522776933)], ['eyes', np.float64(0.4642906869983371)], ['may', np.float64(0.5423574877172779)], ['poured', np.float64(0.426889575572282)], ['dryly', np.float64(0.4814135231948157)], ['tight', np.float64(0.5137098693805254)], ['git', np.float64(0.3195794353093541)], ['brushed', np.float64(0.5347574349999537)], ['hope', np.float64(0.5264070766008192)], ['pan', np.float64(0.5735105985820986)], ['arm', np.float64(0.4643102251750972)], ['slightly', np.float64(0.5747484061115511)], ['follow', np.float64(0.5751141679533556)], ['trip', np.float64(0.5374866839146203)], ['rimmed', np.float64(0.5878621587521347)], ['banging', np.float64(0.5832483320104733)], ['farm', np.float64(0.5963305167123542)], ['manner', np.float64(0.5593055976273115)], ['letter', np.float64(0.5053884636900833)], ['taller', np.float64(0.521356564656725)], ['grin', np.float64(0.5493185513691318)], ['shouldered', np.float64(0.5233627618127066)], ['dance', np.float64(0.5884775993164926)]]
[['wherever', np.float64(0.8710403296908729)], ['hinder', np.float64(0.7732274065910919)], ['passions', np.float64(0.8396382517698129)], ['immediate', np.float64(0.7670970751159393)], ['calls', np.float64(0.804803431592742)], ['application', np.float64(0.8243746678077184)], ['thereof', np.float64(0.780192784401948)], ['sublime', np.float64(0.9412128240932649)], ['dismissed', np.float64(0.784816173489306)], ['rob', np.float64(0.9231304691052747)], ['dispose', np.float64(0.8072247609029712)], ['register', np.float64(0.7913400530199727)], ['countess', np.float64(0.7756480544638447)], ['brute', np.float64(0.766579991114887)], ['maria', np.float64(0.7682849259911173)], ['error', np.float64(0.8327089082255051)], ['vacant', np.float64(0.8123532492687323)], ['blindly', np.float64(0.8002079496245342)], ['pious', np.float64(0.8655522346124223)], ['characteristic', np.float64(0.8861148864132218)], ['instruments', np.float64(0.7854747028559846)], ['contented', np.float64(0.7791332199872223)], ['vegetable', np.float64(0.8639965232784743)], ['thrice', np.float64(0.9389000291814302)], ['glaring', np.float64(0.8200386855758449)], ['telegraph', np.float64(0.7901257883855656)], ['plea', np.float64(0.8663914404022733)], ['conquest', np.float64(0.9200528090502814)], ['blind', np.float64(0.8137928612920726)], ['yielded', np.float64(0.7848460563590323)], ['tube', np.float64(0.7786782672900483)], ['followers', np.float64(0.8009380073059897)], ['spell', np.float64(0.7923245193355495)], ['alluded', np.float64(0.843662972328671)], ['observations', np.float64(0.8094634768397955)], ['stark', np.float64(0.8495374873180932)], ['proposed', np.float64(0.7675172107516699)], ['substantial', np.float64(0.8700323218771174)], ['previously', np.float64(0.8668636521994483)], ['compliments', np.float64(0.7799088371841275)], ['certainty', np.float64(0.7842986274868192)], ['darkly', np.float64(0.866325447628844)], ['revelation', np.float64(0.820009857436261)], ['beheld', np.float64(0.8606615103442877)], ['consulted', np.float64(0.7892939297808382)], ['persuasion', np.float64(0.8552727690726781)], ['chop', np.float64(0.766041024438565)], ['nowadays', np.float64(0.8744677043616387)], ['pupil', np.float64(0.923480782609438)], ['arising', np.float64(0.8172729004435186)]]

In [14]:
models = []
count = 0
for decade in selected_decades:
  model = [decade]
  vectors = np.load(f"/content/eng-fiction-all/sgns/{decade}-w.npy")
  with open(f"/content/eng-fiction-all/sgns/{decade}-vocab.pkl", "rb") as file:
    keys = p.load(file)

  model.append(keys)
  model.append(KeyedVectors(vector_size=vectors.shape[1]))

  model[2].add_vectors(keys, vectors)
  models.append(model)

##Model Testing

In [268]:
def sanitize_list(output_list, model):
  t10ChatGPT = []
  for word in output_list:
    if word in model[1] and np.mean(model[2][word]) != 0:
      t10ChatGPT.append(word)
  return t10ChatGPT

def cosine_similarity(target_word, generated_words, model):
  target_vector = model[2][target_word]

  generated_vectors = [model[2][word] for word in generated_words]

  cos_sim_list = model[2].cosine_similarities(target_vector, generated_vectors)

  return np.mean(cos_sim_list)

In [2]:
with open("word_generations_high.pkl", "rb") as file:
  word_generations_high = p.load(file)
print(word_generations_high)

FileNotFoundError: [Errno 2] No such file or directory: 'word_generations_high.pkl'

In [1]:
cos_sim_high = {}
for target_word in word_generations_high:
  count_dict = {}
  for count in word_generations_high[target_word]:
    decade_dict = {}
    for decade in selected_decades:
      model = models[selected_decades.index(decade)]
      temp_dict = {}
      allowed_prompts = ["ahistorical", "modern", "historical", str(decade)]
      for prompt in allowed_prompts:
        raw_words = word_generations_high[target_word][count][prompt]
        generated_words = sanitize_list(raw_words, model)
        if len(generated_words) == 0:
          temp_dict[prompt] = np.nan
        else:
          temp_dict[prompt] = cosine_similarity(
              target_word,
              generated_words,
              model
          )
      decade_dict[decade] = temp_dict
    count_dict[count] = decade_dict
cos_sim_high[target_word] = count_dict

print(cos_sim_high)

NameError: name 'word_generations_high' is not defined

In [274]:
rows = []
for target_word in cos_sim_high:
  for count in cos_sim_high[target_word]:
    for decade in cos_sim_high[target_word][count]:
      for prompt in cos_sim_high[target_word][count][decade]:
        avg_score = cos_sim_high[target_word][count][decade][prompt]
        rows.append({
            "target_word": target_word,
            "count": count,
            "decade": decade,
            "prompt": prompt,
            "avg_cos_sim": avg_score
        })

df_high = pd.DataFrame(rows)
df_high

df1 = df_high.pivot_table(
    index="prompt",
    columns="decade",
    values="avg_cos_sim",
    aggfunc="mean"
)

df_high["prompt"] = df_high["prompt"].astype(str)

df_high["prompt"] = df_high["prompt"].replace({
    "1950": "historical_decade",
    "1960": "historical_decade",
    "1970": "historical_decade",
    "1980": "historical_decade",
    "1990": "historical_decade"
})

table_high = df_high.pivot_table(
    index="prompt",
    columns="decade",
    values="avg_cos_sim",
    aggfunc="mean"
)

row_order = ["ahistorical", "modern", "historical", "historical_decade"]
table_high = table_high.loc[row_order]

table_high.round(4)

display(Markdown("#Semantic Neighbors' Average Cosine Similarity Value"))
display(table_high)

#Semantic Neighbors' Average Cosine Similarity Value

decade                 1950      1960      1970      1980      1990
prompt
ahistorical        0.183719  0.178866  0.192491  0.186725  0.188839
modern             0.177465  0.172726  0.183540  0.182222  0.182803
historical         0.185385  0.180042  0.191543  0.189651  0.189972
historical_decade  0.184677  0.177789  0.189280  0.185053  0.186862

In [273]:
delta_high = table_high.drop(columns=["Mean"]).subtract(
    table_high.loc["ahistorical"].drop("Mean"),
    axis=1
)

delta_high = delta_high.drop(index="ahistorical")

delta_high.round(4)

display(Markdown("#Delta in Semantic Neighbors Average Cosine Similarity Value"))
display(delta_high)

#Delta in Semantic Neighbors Average Cosine Similarity Value

decade                 1950      1960      1970      1980      1990
prompt
modern            -0.006254 -0.006139 -0.008951 -0.004503 -0.006036
historical         0.001666  0.001177 -0.000948  0.002926  0.001132
historical_decade  0.000957 -0.001076 -0.003211 -0.001672 -0.001977

In [271]:
with open("cos_sim_high.pkl", "wb") as file:
  p.dump(cos_sim_high, file)
print(cos_sim_high)

{'wherever': {0: {1950: {'ahistorical': np.float32(0.18303211), 'modern': np.float32(0.16090406), 'historical': np.float32(0.18852817), '1950': np.float32(0.16824639)}, 1960: {'ahistorical': np.float32(0.1715732), 'modern': np.float32(0.13832623), 'historical': np.float32(0.17031415), '1960': np.float32(0.13832623)}, 1970: {'ahistorical': np.float32(0.17727415), 'modern': np.float32(0.13357982), 'historical': np.float32(0.16405746), '1970': np.float32(0.109700255)}, 1980: {'ahistorical': np.float32(0.12540609), 'modern': np.float32(0.094456814), 'historical': np.float32(0.14771253), '1980': np.float32(0.07018612)}, 1990: {'ahistorical': np.float32(0.110198826), 'modern': np.float32(0.08343455), 'historical': np.float32(0.15210795), '1990': np.float32(0.12343532)}}, 1: {1950: {'ahistorical': np.float32(0.1152833), 'modern': np.float32(0.16459306), 'historical': np.float32(0.18414304), '1950': np.float32(0.18916257)}, 1960: {'ahistorical': np.float32(0.12318877), 'modern': np.float32(0.12649116), 'historical': np.float32(0.15718345), '1960': np.float32(0.14369024)}, 1970: {'ahistorical': np.float32(0.12218501), 'modern': np.float32(0.1393849), 'historical': np.float32(0.16042934), '1970': np.float32(0.11553865)}, 1980: {'ahistorical': np.float32(0.09060268), 'modern': np.float32(0.10522748), 'historical': np.float32(0.10748641), '1980': np.float32(0.0875826)}, 1990: {'ahistorical': np.float32(0.066942036), 'modern': np.float32(0.093048476), 'historical': np.float32(0.11918359), '1990': np.float32(0.10987856)}}, 2: {1950: {'ahistorical': np.float32(0.14856876), 'modern': np.float32(0.1738796), 'historical': np.float32(0.13218229), '1950': np.float32(0.1456854)}, 1960: {'ahistorical': np.float32(0.15020725), 'modern': np.float32(0.13494995), 'historical': np.float32(0.12421545), '1960': np.float32(0.10190789)}, 1970: {'ahistorical': np.float32(0.13945004), 'modern': np.float32(0.15487906), 'historical': np.float32(0.114863984), '1970': np.float32(0.15267485)}, 1980: {'ahistorical': np.float32(0.10675446), 'modern': np.float32(0.11282102), 'historical': np.float32(0.09745976), '1980': np.float32(0.11197235)}, 1990: {'ahistorical': np.float32(0.08808237), 'modern': np.float32(0.09694555), 'historical': np.float32(0.09315243), '1990': np.float32(0.07118158)}}}, 'hinder': {0: {1950: {'ahistorical': np.float32(0.05413653), 'modern': np.float32(-0.017179074), 'historical': np.float32(0.112829775), '1950': np.float32(0.042687017)}, 1960: {'ahistorical': np.float32(0.06482763), 'modern': np.float32(-0.033021435), 'historical': np.float32(0.08188305), '1960': np.float32(0.091038786)}, 1970: {'ahistorical': np.float32(-0.025154572), 'modern': np.float32(-0.089268774), 'historical': np.float32(0.104551405), '1970': np.float32(0.021353118)}, 1980: {'ahistorical': np.float32(0.11274184), 'modern': np.float32(0.09333853), 'historical': np.float32(0.108069286), '1980': np.float32(0.17127576)}, 1990: {'ahistorical': np.float32(0.096850954), 'modern': np.float32(0.019944355), 'historical': np.float32(0.08398501), '1990': np.float32(0.043296833)}}, 1: {1950: {'ahistorical': np.float32(0.12551054), 'modern': np.float32(0.22364703), 'historical': np.float32(0.09314234), '1950': np.float32(0.32184198)}, 1960: {'ahistorical': np.float32(0.091038786), 'modern': np.float32(0.252198), 'historical': np.float32(0.116044424), '1960': np.float32(0.065697394)}, 1970: {'ahistorical': np.float32(0.06547877), 'modern': np.float32(0.20001456), 'historical': np.float32(0.08849041), '1970': np.float32(-0.089268774)}, 1980: {'ahistorical': np.float32(0.10608796), 'modern': np.float32(0.18349871), 'historical': np.float32(0.121849686), '1980': np.float32(0.12160732)}, 1990: {'ahistorical': np.float32(0.05314113), 'modern': np.float32(0.15815255), 'historical': np.float32(0.1293076), '1990': np.float32(0.09355029)}}, 2: {1950: {'ahistorical': nan, 'modern': np.float32(0.12601142), 'historical': np.float32(0.12551057), '1950': np.float32(0.042687017)}, 1960: {'ahistorical': nan, 'modern': np.float32(0.12708426), 'historical': np.float32(0.09103876), '1960': np.float32(-0.035581544)}, 1970: {'ahistorical': nan, 'modern': np.float32(0.11358506), 'historical': np.float32(0.06547878), '1970': np.float32(0.13590036)}, 1980: {'ahistorical': nan, 'modern': np.float32(0.1406305), 'historical': np.float32(0.1228089), '1980': np.float32(0.049275294)}, 1990: {'ahistorical': nan, 'modern': np.float32(0.084726036), 'historical': np.float32(0.1096457), '1990': np.float32(-0.0031586543)}}}, 'passions': {0: {1950: {'ahistorical': np.float32(0.19827247), 'modern': np.float32(0.20138228), 'historical': np.float32(0.279355), '1950': np.float32(0.23140004)}, 1960: {'ahistorical': np.float32(0.20476712), 'modern': np.float32(0.20074546), 'historical': np.float32(0.26268682), '1960': np.float32(0.27538404)}, 1970: {'ahistorical': np.float32(0.2182908), 'modern': np.float32(0.20287374), 'historical': np.float32(0.2829193), '1970': np.float32(0.24231097)}, 1980: {'ahistorical': np.float32(0.22136319), 'modern': np.float32(0.21121678), 'historical': np.float32(0.2678308), '1980': np.float32(0.23053923)}, 1990: {'ahistorical': np.float32(0.19756974), 'modern': np.float32(0.1848819), 'historical': np.float32(0.2557795), '1990': np.float32(0.23583968)}}, 1: {1950: {'ahistorical': np.float32(0.1767509), 'modern': np.float32(0.21076603), 'historical': np.float32(0.1967754), '1950': np.float32(0.24380025)}, 1960: {'ahistorical': np.float32(0.18503076), 'modern': np.float32(0.18982713), 'historical': np.float32(0.20298132), '1960': np.float32(0.21645582)}, 1970: {'ahistorical': np.float32(0.17742841), 'modern': np.float32(0.18642575), 'historical': np.float32(0.21887538), '1970': np.float32(0.23250084)}, 1980: {'ahistorical': np.float32(0.20481013), 'modern': np.float32(0.21199754), 'historical': np.float32(0.21885642), '1980': np.float32(0.20688435)}, 1990: {'ahistorical': np.float32(0.16875915), 'modern': np.float32(0.18415007), 'historical': np.float32(0.22172399), '1990': np.float32(0.21941513)}}, 2: {1950: {'ahistorical': np.float32(0.17705299), 'modern': np.float32(0.1861637), 'historical': np.float32(0.3459974), '1950': np.float32(0.2566386)}, 1960: {'ahistorical': np.float32(0.19350262), 'modern': np.float32(0.18895282), 'historical': np.float32(0.30651498), '1960': np.float32(0.1899293)}, 1970: {'ahistorical': np.float32(0.19214542), 'modern': np.float32(0.19519205), 'historical': np.float32(0.33813336), '1970': np.float32(0.28200468)}, 1980: {'ahistorical': np.float32(0.20971294), 'modern': np.float32(0.21617709), 'historical': np.float32(0.31456771), '1980': np.float32(0.24373503)}, 1990: {'ahistorical': np.float32(0.16678715), 'modern': np.float32(0.18498544), 'historical': np.float32(0.29910025), '1990': np.float32(0.22207525)}}}, 'immediate': {0: {1950: {'ahistorical': np.float32(0.161028), 'modern': np.float32(0.14658642), 'historical': np.float32(0.18221754), '1950': np.float32(0.13379942)}, 1960: {'ahistorical': np.float32(0.16303977), 'modern': np.float32(0.13528797), 'historical': np.float32(0.18042879), '1960': np.float32(0.18143637)}, 1970: {'ahistorical': np.float32(0.18113312), 'modern': np.float32(0.15796633), 'historical': np.float32(0.18924224), '1970': np.float32(0.2119567)}, 1980: {'ahistorical': np.float32(0.20486876), 'modern': np.float32(0.18884921), 'historical': np.float32(0.2074452), '1980': np.float32(0.21052901)}, 1990: {'ahistorical': np.float32(0.19255842), 'modern': np.float32(0.177679), 'historical': np.float32(0.1964328), '1990': np.float32(0.1915326)}}, 1: {1950: {'ahistorical': np.float32(0.19055821), 'modern': np.float32(0.15995389), 'historical': np.float32(0.17676237), '1950': np.float32(0.13761003)}, 1960: {'ahistorical': np.float32(0.19435783), 'modern': np.float32(0.15285648), 'historical': np.float32(0.17546874), '1960': np.float32(0.15064357)}, 1970: {'ahistorical': np.float32(0.20817842), 'modern': np.float32(0.17139772), 'historical': np.float32(0.18935885), '1970': np.float32(0.18315136)}, 1980: {'ahistorical': np.float32(0.23469871), 'modern': np.float32(0.18951847), 'historical': np.float32(0.20034838), '1980': np.float32(0.22558323)}, 1990: {'ahistorical': np.float32(0.23351794), 'modern': np.float32(0.17955978), 'historical': np.float32(0.1883246), '1990': np.float32(0.19215253)}}, 2: {1950: {'ahistorical': np.float32(0.14209247), 'modern': np.float32(0.15966748), 'historical': np.float32(0.1296772), '1950': np.float32(0.12872493)}, 1960: {'ahistorical': np.float32(0.15152362), 'modern': np.float32(0.17339094), 'historical': np.float32(0.12823664), '1960': np.float32(0.18683895)}, 1970: {'ahistorical': np.float32(0.16822428), 'modern': np.float32(0.17656861), 'historical': np.float32(0.1642694), '1970': np.float32(0.19835182)}, 1980: {'ahistorical': np.float32(0.19852482), 'modern': np.float32(0.19139263), 'historical': np.float32(0.1533918), '1980': np.float32(0.2676465)}, 1990: {'ahistorical': np.float32(0.18812287), 'modern': np.float32(0.19583777), 'historical': np.float32(0.15553826), '1990': np.float32(0.1785376)}}}, 'calls': {0: {1950: {'ahistorical': np.float32(0.080467194), 'modern': np.float32(0.06488197), 'historical': np.float32(0.08547741), '1950': np.float32(0.08070956)}, 1960: {'ahistorical': np.float32(0.113839835), 'modern': np.float32(0.05563142), 'historical': np.float32(0.06706577), '1960': np.float32(0.10704257)}, 1970: {'ahistorical': np.float32(0.12761259), 'modern': np.float32(0.08957657), 'historical': np.float32(0.08587487), '1970': np.float32(0.15246147)}, 1980: {'ahistorical': np.float32(0.14346214), 'modern': np.float32(0.10983086), 'historical': np.float32(0.10455154), '1980': np.float32(0.15249257)}, 1990: {'ahistorical': np.float32(0.19244869), 'modern': np.float32(0.14328605), 'historical': np.float32(0.1040646), '1990': np.float32(0.17751077)}}, 1: {1950: {'ahistorical': np.float32(0.042031348), 'modern': np.float32(0.11358571), 'historical': np.float32(0.08416946), '1950': np.float32(0.07048115)}, 1960: {'ahistorical': np.float32(0.07961207), 'modern': np.float32(0.119108446), 'historical': np.float32(0.0743609), '1960': np.float32(0.15382984)}, 1970: {'ahistorical': np.float32(0.07555069), 'modern': np.float32(0.13514069), 'historical': np.float32(0.10293388), '1970': np.float32(0.12383069)}, 1980: {'ahistorical': np.float32(0.12512848), 'modern': np.float32(0.14623915), 'historical': np.float32(0.099516794), '1980': np.float32(0.10649917)}, 1990: {'ahistorical': np.float32(0.14714856), 'modern': np.float32(0.21086213), 'historical': np.float32(0.086985365), '1990': np.float32(0.17166647)}}, 2: {1950: {'ahistorical': np.float32(0.07183109), 'modern': np.float32(0.07646467), 'historical': np.float32(0.0693652), '1950': np.float32(0.094029434)}, 1960: {'ahistorical': np.float32(0.0772583), 'modern': np.float32(0.0944683), 'historical': np.float32(0.072066754), '1960': np.float32(0.10686453)}, 1970: {'ahistorical': np.float32(0.09926102), 'modern': np.float32(0.09964702), 'historical': np.float32(0.102515504), '1970': np.float32(0.15246147)}, 1980: {'ahistorical': np.float32(0.13198562), 'modern': np.float32(0.12511407), 'historical': np.float32(0.09006146), '1980': np.float32(0.16746606)}, 1990: {'ahistorical': np.float32(0.17517833), 'modern': np.float32(0.1810409), 'historical': np.float32(0.09921671), '1990': np.float32(0.17280038)}}}, 'application': {0: {1950: {'ahistorical': np.float32(0.16942419), 'modern': np.float32(0.16612597), 'historical': np.float32(0.14610663), '1950': np.float32(0.18042989)}, 1960: {'ahistorical': np.float32(0.15708871), 'modern': np.float32(0.12836489), 'historical': np.float32(0.1594556), '1960': np.float32(0.18528716)}, 1970: {'ahistorical': np.float32(0.1898576), 'modern': np.float32(0.18635845), 'historical': np.float32(0.17959224), '1970': np.float32(0.20123385)}, 1980: {'ahistorical': np.float32(0.16761541), 'modern': np.float32(0.17803861), 'historical': np.float32(0.13695934), '1980': np.float32(0.13611978)}, 1990: {'ahistorical': np.float32(0.1922807), 'modern': np.float32(0.18789272), 'historical': np.float32(0.15242311), '1990': np.float32(0.14076026)}}, 1: {1950: {'ahistorical': np.float32(0.1758451), 'modern': np.float32(0.15958792), 'historical': np.float32(0.19504657), '1950': np.float32(0.18766809)}, 1960: {'ahistorical': np.float32(0.18154287), 'modern': np.float32(0.14899862), 'historical': np.float32(0.21301529), '1960': np.float32(0.19434562)}, 1970: {'ahistorical': np.float32(0.22925913), 'modern': np.float32(0.18643503), 'historical': np.float32(0.22075687), '1970': np.float32(0.20467407)}, 1980: {'ahistorical': np.float32(0.14613125), 'modern': np.float32(0.12698366), 'historical': np.float32(0.1988847), '1980': np.float32(0.18019785)}, 1990: {'ahistorical': np.float32(0.15620561), 'modern': np.float32(0.15483092), 'historical': np.float32(0.18256824), '1990': np.float32(0.13345522)}}, 2: {1950: {'ahistorical': np.float32(0.20595203), 'modern': np.float32(0.15644391), 'historical': np.float32(0.18651299), '1950': np.float32(0.18741654)}, 1960: {'ahistorical': np.float32(0.16687326), 'modern': np.float32(0.14911303), 'historical': np.float32(0.22246273), '1960': np.float32(0.22567639)}, 1970: {'ahistorical': np.float32(0.19081378), 'modern': np.float32(0.1860278), 'historical': np.float32(0.23005316), '1970': np.float32(0.20601647)}, 1980: {'ahistorical': np.float32(0.16302474), 'modern': np.float32(0.1553878), 'historical': np.float32(0.21721098), '1980': np.float32(0.15481365)}, 1990: {'ahistorical': np.float32(0.19967115), 'modern': np.float32(0.1572435), 'historical': np.float32(0.20250218), '1990': np.float32(0.1793152)}}}, 'thereof': {0: {1950: {'ahistorical': np.float32(0.13829604), 'modern': np.float32(0.10115585), 'historical': np.float32(0.12984182), '1950': np.float32(0.12587017)}, 1960: {'ahistorical': np.float32(0.09183484), 'modern': np.float32(0.078415744), 'historical': np.float32(0.11710123), '1960': np.float32(0.11061969)}, 1970: {'ahistorical': np.float32(0.15186824), 'modern': np.float32(0.12649252), 'historical': np.float32(0.13660479), '1970': np.float32(0.12945639)}, 1980: {'ahistorical': np.float32(0.13331105), 'modern': np.float32(0.10479402), 'historical': np.float32(0.10481404), '1980': np.float32(0.14192417)}, 1990: {'ahistorical': np.float32(0.1256558), 'modern': np.float32(0.114225596), 'historical': np.float32(0.119816944), '1990': np.float32(0.14264)}}, 1: {1950: {'ahistorical': np.float32(0.13829604), 'modern': np.float32(0.10064653), 'historical': nan, '1950': np.float32(0.10652797)}, 1960: {'ahistorical': np.float32(0.098707065), 'modern': np.float32(0.08413498), 'historical': nan, '1960': np.float32(0.09706396)}, 1970: {'ahistorical': np.float32(0.15186824), 'modern': np.float32(0.15121715), 'historical': nan, '1970': np.float32(0.17539173)}, 1980: {'ahistorical': np.float32(0.13941325), 'modern': np.float32(0.10817094), 'historical': nan, '1980': np.float32(0.10142148)}, 1990: {'ahistorical': np.float32(0.14700884), 'modern': np.float32(0.13727938), 'historical': nan, '1990': np.float32(0.12008113)}}, 2: {1950: {'ahistorical': np.float32(0.13150512), 'modern': np.float32(0.088812195), 'historical': np.float32(0.12269581), '1950': np.float32(0.100062355)}, 1960: {'ahistorical': np.float32(0.12223616), 'modern': np.float32(0.10228034), 'historical': np.float32(0.10853333), '1960': np.float32(0.11762759)}, 1970: {'ahistorical': np.float32(0.15448229), 'modern': np.float32(0.11969831), 'historical': np.float32(0.16252583), '1970': np.float32(0.12799603)}, 1980: {'ahistorical': np.float32(0.11802392), 'modern': np.float32(0.108185045), 'historical': np.float32(0.13083604), '1980': np.float32(0.1660227)}, 1990: {'ahistorical': np.float32(0.13934034), 'modern': np.float32(0.08801461), 'historical': np.float32(0.13282855), '1990': np.float32(0.12530863)}}}, 'sublime': {0: {1950: {'ahistorical': np.float32(0.22641519), 'modern': np.float32(0.2320157), 'historical': np.float32(0.22825186), '1950': np.float32(0.28167182)}, 1960: {'ahistorical': np.float32(0.2525281), 'modern': np.float32(0.2689774), 'historical': np.float32(0.21639127), '1960': np.float32(0.24115117)}, 1970: {'ahistorical': np.float32(0.23296845), 'modern': np.float32(0.25305465), 'historical': np.float32(0.22477944), '1970': np.float32(0.22879982)}, 1980: {'ahistorical': np.float32(0.24608612), 'modern': np.float32(0.26213756), 'historical': np.float32(0.2506156), '1980': np.float32(0.27822727)}, 1990: {'ahistorical': np.float32(0.2734236), 'modern': np.float32(0.28687522), 'historical': np.float32(0.27194148), '1990': np.float32(0.27578998)}}, 1: {1950: {'ahistorical': np.float32(0.24938445), 'modern': np.float32(0.22946337), 'historical': np.float32(0.22213814), '1950': np.float32(0.22333619)}, 1960: {'ahistorical': np.float32(0.24601132), 'modern': np.float32(0.2190348), 'historical': np.float32(0.19250412), '1960': np.float32(0.2412472)}, 1970: {'ahistorical': np.float32(0.2554435), 'modern': np.float32(0.25236252), 'historical': np.float32(0.23095639), '1970': np.float32(0.25184298)}, 1980: {'ahistorical': np.float32(0.24406525), 'modern': np.float32(0.24503888), 'historical': np.float32(0.27076837), '1980': np.float32(0.23469877)}, 1990: {'ahistorical': np.float32(0.25220188), 'modern': np.float32(0.28343523), 'historical': np.float32(0.28635868), '1990': np.float32(0.2614452)}}, 2: {1950: {'ahistorical': np.float32(0.2581023), 'modern': np.float32(0.21592525), 'historical': np.float32(0.2257066), '1950': np.float32(0.218363)}, 1960: {'ahistorical': np.float32(0.23404633), 'modern': np.float32(0.22000444), 'historical': np.float32(0.21505368), '1960': np.float32(0.25276217)}, 1970: {'ahistorical': np.float32(0.2417985), 'modern': np.float32(0.23207381), 'historical': np.float32(0.23093253), '1970': np.float32(0.25461352)}, 1980: {'ahistorical': np.float32(0.23692346), 'modern': np.float32(0.24502033), 'historical': np.float32(0.22126873), '1980': np.float32(0.2377955)}, 1990: {'ahistorical': np.float32(0.28421047), 'modern': np.float32(0.26391888), 'historical': np.float32(0.26667136), '1990': np.float32(0.26185107)}}}, 'dismissed': {0: {1950: {'ahistorical': np.float32(0.091575414), 'modern': np.float32(0.1084313), 'historical': np.float32(0.09398867), '1950': np.float32(0.10276697)}, 1960: {'ahistorical': np.float32(0.13529429), 'modern': np.float32(0.10702526), 'historical': np.float32(0.16815186), '1960': np.float32(0.1344001)}, 1970: {'ahistorical': np.float32(0.15663436), 'modern': np.float32(0.15078011), 'historical': np.float32(0.18710706), '1970': np.float32(0.13776569)}, 1980: {'ahistorical': np.float32(0.15818377), 'modern': np.float32(0.15833102), 'historical': np.float32(0.16906135), '1980': np.float32(0.1147875)}, 1990: {'ahistorical': np.float32(0.14142564), 'modern': np.float32(0.14120793), 'historical': np.float32(0.13641627), '1990': np.float32(0.1439892)}}, 1: {1950: {'ahistorical': np.float32(0.12040999), 'modern': np.float32(0.10020725), 'historical': np.float32(0.06739007), '1950': np.float32(0.08659194)}, 1960: {'ahistorical': np.float32(0.15946709), 'modern': np.float32(0.1291844), 'historical': np.float32(0.115764715), '1960': np.float32(0.14693427)}, 1970: {'ahistorical': np.float32(0.16536914), 'modern': np.float32(0.16675344), 'historical': np.float32(0.14936554), '1970': np.float32(0.15577228)}, 1980: {'ahistorical': np.float32(0.16557612), 'modern': np.float32(0.15853056), 'historical': np.float32(0.13963468), '1980': np.float32(0.1543886)}, 1990: {'ahistorical': np.float32(0.16859199), 'modern': np.float32(0.15383612), 'historical': np.float32(0.12703824), '1990': np.float32(0.16754851)}}, 2: {1950: {'ahistorical': np.float32(0.09704986), 'modern': np.float32(0.09387604), 'historical': np.float32(0.09533066), '1950': np.float32(0.104623616)}, 1960: {'ahistorical': np.float32(0.12321296), 'modern': np.float32(0.108897544), 'historical': np.float32(0.14519933), '1960': np.float32(0.11475899)}, 1970: {'ahistorical': n